var express = require('express')
var router = require('./router')
var db= require('./dbconnect')
var cors= require('cors')
var app = express()
var bodyParser = require('body-parser')
app.use(bodyParser.json())
app.use(cors())
app.use('/', router)
app.listen(4000, () => { console.log("connected") })
